### ISSUE TITLE
First request takes long time with AIS2031 mode enabled

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#23]
Test setup:
1) configure esdm with -Dais2031=true
2) start esdm-server and wait some time (e.g. 20s), all DRGs should be fully seeded now
3) connect client and request random numbers -> esdm needs around 1-2s on my system until it returns random numbers on the first request
4) connect client again -> random numbers are returned instantly

Without ais2031 I obtain random numbers instantly in step 3.

**Comment by smuellerDD** [comment]
Am Donnerstag, 29. Juni 2023, 21:22:42 CEST schrieb Markus Theil:

Hi Markus,

> Test setup:
> 1) configure esdm with -Dais2031=true
> 2) start esdm-server and wait some time (e.g. 20s), all DRGs should be fully
> seeded now 3) connect client and request random numbers -> esdm needs
> around 1-2s on my system until it returns random numbers on the first
> request 4) connect client again -> random numbers are returned instantly
> 
> Without ais2031 I obtain random numbers instantly in step 3.

The issue is that AIS20/31 requires 2 entropy sources where each delivers 220 
bits of entropy for initially seeding a DRNG. Thus, could you please send me 
the log of the server with the AIS20/31 support enabled? I could suspect that 
the 2nd entropy source is, say, the IRQ entropy source on an otherwise quiet 
system which does not deliver entropy for even the first DRNG in a suitable 
amount of time.


Ciao
Stephan
