### ISSUE TITLE
write_wakeup_threshold does not work

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#35]
I tested a smartcard-like setup (watch auxiliary pool and feed entropy in it, while additional entropy sources where active). The output of /proc/sys/kernel/random/entropy_avail dropped to 0 when I started an endless loop drawing random numbers from ESDM with prediction resistance. My small helper which selects on /dev/random for writeability only gets notified once and not permanently, while my test tool is running. The tests seem to not cover this case of multiple write readiness notifications.

**Comment by thillux** [comment]
Maybe something like this is missing:
```diff
diff --git a/esdm/esdm_es_aux.c b/esdm/esdm_es_aux.c
index 1b73a5c..8edac75 100644
--- a/esdm/esdm_es_aux.c
+++ b/esdm/esdm_es_aux.c
@@ -104,6 +104,8 @@ static void esdm_set_digestsize(uint32_t digestsize)
         */
        ent_bits = min_uint32(ent_bits, old_digestsize);
        atomic_add(&pool->aux_entropy_bits, (int)ent_bits);
+
+       esdm_shm_status_set_need_entropy();
 }

 static void esdm_init_wakeup_bits(void)
@@ -367,6 +369,8 @@ static uint32_t esdm_aux_get_pool(uint8_t *outbuf, uint32_t requested_bits)
                memcpy(outbuf, aux_output, requested_bits >> 3);
        }

+       esdm_shm_status_set_need_entropy();
+
        mutex_reader_unlock(&drng->hash_lock);
        memset_secure(aux_output, 0, digestsize);
        return returned_ent_bits;
```

**Comment by thillux** [comment]
After patching ESDM like shown above, esdm-cuse-* seems to deadlock in esdm_cuse_shm_status_down after some time (on sem_wait).

**Comment by thillux** [comment]
```diff
diff --git a/frontends/cuse/cuse_device.c b/frontends/cuse/cuse_device.c
index bf0a0db..8c74021 100644
--- a/frontends/cuse/cuse_device.c
+++ b/frontends/cuse/cuse_device.c
@@ -172,8 +172,10 @@ static void esdm_cuse_shm_status_down(void)
        /* Wait and block until the SHM-Segment becomes available */
        while (!esdm_cuse_shm_status_avail())
                nanosleep(&ts, NULL);
-
-       if (sem_wait(esdm_cuse_semid))
+
+       ts.tv_sec = 1;
+       ts.tv_nsec = 0;
+       if (sem_timedwait(esdm_cuse_semid, &ts) && errno != ETIMEDOUT)
                logger(LOGGER_ERR, LOGGER_C_CUSE, "Cannot use semaphore\n");
 }
```

**Comment by thillux** [comment]
This seems to work for me. I assume sem_post could also block. I guess it can be converted to semtimedop.

**Comment by smuellerDD** [comment]
Am Freitag, 22. September 2023, 20:30:31 CEST schrieb Markus Theil:

Hi Markus,

This patch seems to be perhaps curing the symptoms but not the cause.

> Maybe something like this is missing:
> ```diff
> diff --git a/esdm/esdm_es_aux.c b/esdm/esdm_es_aux.c
> index 1b73a5c..8edac75 100644
> --- a/esdm/esdm_es_aux.c
> +++ b/esdm/esdm_es_aux.c
> @@ -104,6 +104,8 @@ static void esdm_set_digestsize(uint32_t digestsize)
>          */
>         ent_bits = min_uint32(ent_bits, old_digestsize);
>         atomic_add(&pool->aux_entropy_bits, (int)ent_bits);
> +
> +       esdm_shm_status_set_need_entropy();
>  }

As of now, this function is dead code - the set_digestssize is only used for 
switching the hash. That hash switch is currently not used at all.
> 
>  static void esdm_init_wakeup_bits(void)
> @@ -367,6 +369,8 @@ static uint32_t esdm_aux_get_pool(uint8_t *outbuf,
> uint32_t requested_bits) memcpy(outbuf, aux_output, requested_bits >> 3);
>         }
> 
> +       esdm_shm_status_set_need_entropy();
> +
>         mutex_reader_unlock(&drng->hash_lock);
>         memset_secure(aux_output, 0, digestsize);
>         return returned_ent_bits;
> ```

Here I am unsure. First, the need_entropy call should be called outside the 
lock. Yet, I am wondering, because the get_pool function is called from 
esdm_fill_seed_buffer() which at the end calls esdm_writer_wakeup(). The 
wakeup call does invoke the esdm_shm_status_set_need_entropy.

So, somehow I am not understanding why this addition would address the issue 
you describe.

Just to clarify, your scenario is:

1. you have a reader causing frequent reseeds

2. entropy_avail (which *only* reflects the contents of the aux_pool) drops to 
0. This means you have had some external writer that filled the aux_pool as 
otherwise the aux_pool would remain at 0.

3. you select on /dev/random for writability and you are not woken up.

In my case, that works: when I add at the end to esdm_shm_status_up a hint 
that the semaphore fires, it is picked up with the cuse-random 
esdm_cuse_shm_status_down and triggers the poll.

So, my rngd does wake up:

jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Inject entropy into input pool
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random

Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,

I was not able to reproduce the issue with the latest patch :+1: 

BR
Markus
