### ISSUE TITLE
v1.1.1: Behaviour of esdm_aux_timedwait_for_need_entropy for current entropy level 0

### ISSUE THREAD

**Issue by myrkr** [smuellerDD/esdm#50]
I did some testing with this function. I detected a problem in the following scenario:

- our external source of entropy is no longer available
- we query for random data using esdm_rpcc_get_random_bytes_full
- as expected the entropy count sinks the 256 and then 0 in intervals of about 10 minutes due to reseeding operation
- however, as soon as the entropy count is 0 the function esdm_aux_timedwait_for_need_entropy does not return until the timeout is reached

I would have expected that the function immediately returns with 0 in this case.

This is especially a problem when the external entropy source is available again. We could provide some via esdm_rpcc_rnd_add_entropy but are still waiting for the signalling of the need for it.

I considered checking for an entropy count of 0 before calling that function but this would be racy.

**Comment by smuellerDD** [comment]
Am Mittwoch, 7. August 2024, 13:23:21 MESZ schrieb Torsten Hilbrich:

Hi Torsten,

> I did some testing with this function. I detected a problem in the following
> scenario:
> 
> - our external source of entropy is no longer available
> - we query for random data using esdm_rpcc_get_random_bytes_full
> - as expected the entropy count sinks the 256 and then 0 in intervals of
> about 10 minutes due to reseeding operation - however, as soon as the
> entropy count is 0 the function esdm_aux_timedwait_for_need_entropy does
> not return until the timeout is reached
> 
> I would have expected that the function immediately returns with 0 in this
> case.

Hm, the sem_post / sem_wait is level-triggered. I.e. if the sem_post for 
requesting new entropy is set, the semaphore is incremented. Thus, if a caller 
newly attaches, and issues a sem_wait, the wait immediately returns. I have 
tested this with cuse.

That said, the need_entropy is only invoked from the aux pool. That said, the 
wakeup only happens if esdm_need_entropy returns true. It returns true if the 
aux entropy value is lower than the write wakeup value. 

Thus, what is this value?

What is the content of the semaphore? I.e. does it fire immediately with the 
sem_wait / sem_clockwait?
> 
> This is especially a problem when the external entropy source is available
> again. We could provide some via esdm_rpcc_rnd_add_entropy but are still
> waiting for the signalling of the need for it.

Agreed, but I know I tested this with the cuse daemons. Of course, something 
could have been broken, though.
> 
> I considered checking for an entropy count of 0 before calling that function
> but this would be racy.


Ciao
Stephan

**Comment by myrkr** [comment]
I did another test with the semaphore here:

- `esdm-tool -r`: read 4 bytes of random with esdm_rpcc_get_random_bytes_full
- `esdm-tool -g`: query the entropy count with esdm_rpcc_rnd_get_ent_cnt
- `esdm-tool -w`: performs the call to esdm_aux_timedwait_for_need_entropy after initialization

Here is a typescript:

```
[localhost:~] esdm-tool -d
 esdm server status: ESDM library version: 1.1.1
DRNG name: builtin SP800-90A Hash DRBG
ESDM security strength in bits: 256
Number of DRNG instances: 4
Standards compliance: NTG.1(2011) 
ESDM minimally seeded: true
ESDM fully seeded: true
ESDM entropy level: 0
Entropy Source 0 properties:
 Name: Auxiliary
 Hash for operating entropy pool: builtin SHA-512
 Available entropy: 0

esdm-tool succeeded!
[localhost:~] esdm-tool -g
0
[localhost:~] esdm-tool -r
get_good_random buf_size: 4 timeout: 5 threadid 6418
get_good_random result: 0 threadid 6418
esdm-tool failed!
[localhost:~] time esdm-tool -w
^C

real	0m4.023s
user	0m0.004s
sys	0m0.003s
[localhost:~] hexdump -C /dev/sem.esdm-need-entropy-level-semaphore
00000000  00 00 00 00 05 00 00 00  80 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020
```

My assumption was that `esdm-tool -w` should immediately return if no entropy is available.

**Comment by myrkr** [comment]
I did initialize the entropy pool with the `esdm-tool -e` before doing the test.

I just repeated the test with the following steps:

- Starting the esdm-server
- `esdm-tool -g` report 0
- `esdm-tool -e; esdm-tool -g` reports 512
- `esdm-tool -r; esdm-tool -g` report 256
- `esdm-tool -r; esdm-tool -g` report 0
- first call to `esdm-tool -w` reports that entropy is needed
- second call to `esdm-tool -w` is blocking
- `esdm-tool -g` reports 0

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. August 2024, 10:19:50 MESZ schrieb Torsten Hilbrich:

Hi Torsten,

> I did initialize the entropy pool with the `esdm-tool -e` before doing the
> test.
> 
> I just repeated the test with the following steps:
> 
> - Starting the esdm-server
> - `esdm-tool -g` report 0
> - `esdm-tool -e; esdm-tool -g` reports 512
> - `esdm-tool -r; esdm-tool -g` report 256
> - `esdm-tool -r; esdm-tool -g` report 0
> - first call to `esdm-tool -w` reports that entropy is needed
> - second call to `esdm-tool -w` is blocking

The issue is here:

the first call with -w "consumes" the trigger, i.e. resets it. So, the 
semaphore in this case has successfully fired, but the caller did not provide 
any entropy, which I would infer as an error from the caller. Or perhaps not 
so, because the caller was unable to provide entropy at this point - so it is 
arguably what is right or wrong.

But I think the ESDM should gracefully handle such "real or perceived" wrong 
usage of the caller. I only see one solution: enhance the aux library to 
attach to the ESDM SHM segment and also check for the boolean "need_entropy".

E.g. esdm_cuse_shm_status_down would do:

if (shm->need_entropy)
	return 0;

return sem_clockwait();


What is your take on that?



> - `esdm-tool -g` reports 0

So, here my patch will not change anything - it only changes the startup 
behavior.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. August 2024, 21:17:38 MESZ schrieb Markus Theil:

Hi Markus,

> Hi Stephan and Torsten,
> 
> ```
> if (shm->need_entropy)
> 	return 0;
> XXX
> return sem_clockwait();
> ```
> 
> This can also be racy, if entropy reaches 0 at XXX due to another call. The
> best I can think of is probably something like a Unix socket, where a
> seeder application, like your smartcard-based feeder can listen to
> notification messages and act up on them.
> 
> Instead of dealing with the semaphore count, ESDM would then send such a
> notification to all connected applications. Probably NON_BLOCKING, such
> that full application buffers do not block ESDM on writes.

I agree with all what you say. However, I feel that it is not helpful to re-
architect this approach due to the following: As outlined before, I think the 
caller made an error if (a) it waited for the notification and (b) consumed 
it, but did nothing (i.e. inject entropy). If the caller at the time of 
receipt of the notification cannot inject entropy, it has to handle it like 
remember that and get back to the ESDM with entropy as soon as it can.

That said, as the ESDM shall always protect itself and be graceful to 
erroneous clients, I think it should gracefully handle it. Actually, it is not 
the ESDM server but the aux library that ought to handle it in a more graceful 
manner. IMHO this would be handled with the racy code above. Thus, I think I 
personally can live with the race as it actually should never be triggered in 
the first place.

This is also exactly the same approach as /dev/random does it when you epoll 
it or select it.


The only real question IMHO would be if there is a malicious user that 
sem_wait() and consumes the trigger before the valid caller gets to it. That 
question goes beyond the discussed problem, however as it discusses the use of 
sem_wait/sem_post. If you think this is truly the issue, the caller can 
sem_timedwaid() and check the ->need_entropy SHM flag periodically.

Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,

yes, I agree. Adding the additional check of shm->need_entropy and also attaching the auxiliary library to the shm area should be sufficient here.

BR
Markus

**Comment by myrkr** [comment]
I have now tested with remembering the last result of checking the semaphore and only resetting it once some entropy was successfully supplied to the esdm server. With that modification the testing scenario with resuming correctly after reinserting the smartcard as entropy source was working correctly.

**Comment by smuellerDD** [comment]
Am Freitag, 9. August 2024, 12:06:00 MESZ schrieb Markus Theil:

Hi Markus,

> Hi Stephan,
> 
> yes, I agree. Adding the additional check of shm->need_entropy and also
> attaching the auxiliary library to the shm area should be sufficient here.

I just pushed a patch. Let me know what you think.
> 
> BR
> Markus


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 9. August 2024, 13:06:33 MESZ schrieb Torsten Hilbrich:

Hi Torsten,

> I have now tested with remembering the last result of checking the semaphore
> and only resetting it once some entropy was successfully supplied to the
> esdm server. With that modification the testing scenario with resuming
> correctly after reinserting the smartcard as entropy source was working
> correctly.

Great. As requested by Markus, I have pushed the patch anyhow, because I think 
it makes life easier.
> 
> Torsten


Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,

your change looks good and worked so far in my tests. The issue can be closed from my side. Thanks for adding the early exit path!

BR
Markus
