### ISSUE TITLE
v0.6.0ff: Internal entropy level reported in logs and externally visible entropy level do not match

### ISSUE THREAD

**Issue by myrkr** [smuellerDD/esdm#51]
During some tests before and after updating from version v0.6.0 to version v1.1.1 I noticed that I see log messages like:

```
2024-08-06 10:38:20.714 esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc7) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:511]: [0mreseed triggered by system events for DRNG on node 2
2024-08-06 10:38:20.715 esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc7) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: [0mobtained 256 bits by collecting 256 bits of entropy from aux pool, 256 bits of entropy remaining
2024-08-06 10:38:20.715 esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc8) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:511]: [0mreseed triggered by system events for DRNG on node 3
2024-08-06 10:38:20.715 esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc8) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: [0mobtained 256 bits by collecting 256 bits of entropy from aux pool, 0 bits of entropy remaining
2024-08-06 10:38:20.717 esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc7) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:511]: [0mreseed triggered by system events for DRNG on node 0
2024-08-06 10:38:20.717 esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc7) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: [0mobtained 0 bits by collecting 0 bits of entropy from aux pool, 0 bits of entropy remaining
```

in the logs of the esdm-server but the entropy count queried by `esdm_rpcc_rnd_get_ent_cn` does not changes. Only when some random is consume by calling `esdm_rpcc_get_random_bytes_full` the entropy count returned by that function is updated.

This caused some confusion during some tests as I was testing the behaviour without supplying entropy to the axillary pool but failed to run a test program fetching random data from esdm in parallel. In this case the entropy count was never reduced from 512 byte even after running the tests for hours.

**Comment by smuellerDD** [comment]
Am Mittwoch, 7. August 2024, 13:30:44 MESZ schrieb Torsten Hilbrich:

Hi Torsten,

> During some tests before and after updating from version v0.6.0 to version
> v1.1.1 I noticed that I see log messages like:
> 
> ```
> 2024-08-06 10:38:20.714 esdm-server.service: [34mESDM (10:38:20) (ESDM
> hdl_rpc7) Debug - DRNG
> [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:511]: [0mreseed triggered
> by system events for DRNG on node 2 2024-08-06 10:38:20.715
> esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc7) Debug - Entropy
> Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: [0mobtained 256 bits
> by collecting 256 bits of entropy from aux pool, 256 bits of entropy
> remaining 2024-08-06 10:38:20.715 esdm-server.service: [34mESDM (10:38:20)
> (ESDM hdl_rpc8) Debug - DRNG
> [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:511]: [0mreseed triggered
> by system events for DRNG on node 3 2024-08-06 10:38:20.715
> esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc8) Debug - Entropy
> Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: [0mobtained 256 bits
> by collecting 256 bits of entropy from aux pool, 0 bits of entropy
> remaining 2024-08-06 10:38:20.717 esdm-server.service: [34mESDM (10:38:20)
> (ESDM hdl_rpc7) Debug - DRNG
> [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:511]: [0mreseed triggered
> by system events for DRNG on node 0 2024-08-06 10:38:20.717
> esdm-server.service: [34mESDM (10:38:20) (ESDM hdl_rpc7) Debug - Entropy
> Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: [0mobtained 0 bits
> by collecting 0 bits of entropy from aux pool, 0 bits of entropy remaining
> ```
> 
> in the logs of the esdm-server but the entropy count queried by
> `esdm_rpcc_rnd_get_ent_cn` does not changes. Only when some random is
> consume by calling `esdm_rpcc_get_random_bytes_full` the entropy count
> returned by that function is updated.

Perhaps the following change triggered the issue?

de448324f139a9e1e522fe6c3452d588adee8490

The issue was that the rngd looked at the /proc/sys/random/avail_entropy to 
govern its behavior. After discussing with the rngd maintainer, the value can 
only reflect the aux pool, not the rest.


On the other hand, the following log says that 256 bits are pulled from the 
aux pool and the aux pool has 0 bits remaining:

Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: 
[0mobtained 256 bits by collecting 256 bits of entropy from aux pool, 0 bits 
of entropy remaining

Before the call, get_ent_cnt should return 256 bits and after 0 bits. This is 
goverend by esdm_avail_entropy_aux -> esdm_aux_avail_entropy
> 
> This caused some confusion during some tests as I was testing the behaviour
> without supplying entropy to the axillary pool but failed to run a test
> program fetching random data from esdm in parallel. In this case the
> entropy count was never reduced from 512 byte even after running the tests
> for hours.


So, you are saying that the ent_cnt value remains at 512 even after the afore 
mentioned log would have shown that the aux pool supplied entropy during 
reseeding and reduced its entropy count from, say, 512 bits to 256 bits?


Ciao
Stephan

**Comment by myrkr** [comment]
I now did another test with a version of esdm-version where the esdm_drng_reseed_max_time was set down to 60s.

I used a tool esdm-tool with the following options:

- `-e`: feed 512 bit of entropy with esdm_rpcc_rnd_add_entropy
- `-g`: query the entropy count with esdm_rpcc_rnd_get_ent_cnt
- `-r`: read 4 bytes of random with esdm_rpcc_get_random_bytes_full

I tested the following sequence after starting up "esdm-server -vvvvv":

- `esdm-tool -g`: outputs 0
- `esdm-tool -e; esdm-tool -g`: outputs 512
- `sleep 70; date`: outputs 07:03:35 for the time
- `esdm-tool -e; esdm-tool -r; esdm-tool -e`: outputs first 512; then 256
- `sleep 70; date`: outputs 07:04:45 for the time
- `esdm-tool -e; esdm-tool -r; esdm-tool -e`: outputs first 256; then 512

According to the [esdm.log](https://github.com/user-attachments/files/16539125/esdm.log) file the following times entropy was consumed:

```
ESDM (07:03:35) (ESDM hdl_rpc5) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: obtained 256 bits by collecting 256 bits of entropy from aux pool, 256 bits of entropy remaining
...
ESDM (07:04:45) (ESDM hdl_rpc5) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:351]: obtained 256 bits by collecting 256 bits of entropy from aux pool, 0 bits of entropy remaining
```

This seems to be the exact time that the reseed operation is taking place while fetching random data with `esdm-tool -r`. I previously was under the impression that the reseed operation is time-based. But I also found the following note in the code:

```
/*
 * Maximum number of seconds between DRNG reseed intervals of the DRNG. Note,
 * this is enforced with the next request of random numbers from the
 * DRNG. Setting this value to zero implies a reseeding attempt before every
 * generated random number.
 */
```

So I was probably only under the wrong assumption that the reseed is actually happening after esdm_drng_reseed_max_time seconds.

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. August 2024, 09:17:09 MESZ schrieb Torsten Hilbrich:

Hi Torsten,

Thank you for your retest.

> So I was probably only under the wrong assumption that the reseed is
> actually happening after esdm_drng_reseed_max_time seconds.

You are right. The issue is that there is no separate monitor (which would 
need to be in a separate thread or implemented with some form of alarm) that 
actively reseeds the DRNG when the threshold hits.

This is due to the following considerations: a DRNG reseed only makes sense 
when there is truly somebody wanting random numbers. Assume the following: you 
have a DRNG which is not used for 24 hours: what sense does it make to draw 
entropy every esdm_drng_reseed_max_time and strain the entropy sources? Thus, 
the ESDM triggers the reseed during the next call (but before the DRNG 
actually produces output). This is to limit the strain on the ES and avoid 
unnecessary CPU time.

Do you think something is wrong?

Ciao
Stephan

**Comment by myrkr** [comment]
I think the behaviour is okay. Closing this ticket now, it was basically a wrong understanding on my side how esdm is internally working here regarding the reseed operation.
